site_name: CFI Documentation
nav:
  -  Product Templates:  'Product-Templates.md'
  -  Zoom Single Class:  'Zoom-Single-Class.md'
  -  Pre Recorded Class:  'Pre-Recorded-Class.md'
  -  Custom Fitness:
      -  Lectures:  'Custom-Fitness/Lectures.md'
      -  Videos:  'Custom-Fitness/Videos.md'
      -  Program Section:  'Custom-Fitness/Program-Section.md'
      -  Custom Fitness Program:  'Custom-Fitness/Custom-Fitness-Program.md'
theme:
  name: material
  features:
    - instant
  font:
    text: Inter
    code: Source Code Pro
  palette:
      primary: indigo
      accent: blue

plugins:
  - search:
      prebuild_index: true
      lang:
        - en
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde