site_name: CFI Documentation
nav:
  -  Product Category:  'Product-Category.md'
  -  Product Templates:  'Product-Templates.md'
  -  Zoom Single Class:  'Zoom-Single-Class.md'
  -  Pre Recorded Class:  'Pre-Recorded-Class.md'
  -  Custom Fitness Programs:
      -  Introduction:  'Custom-Fitness-Programs/Introduction.md'
      -  Lectures:  'Custom-Fitness-Programs/Lectures.md'
      -  Program Section:  'Custom-Fitness-Programs/Program-Section.md'
      -  Custom Fitness Program:  'Custom-Fitness-Programs/Custom-Fitness-Program.md'
  -  Goal Based Fitness Plans:
      -  Introduction:  'Goal-Based-Fitness-Plans/Introduction.md'
      -  Lectures:  'Goal-Based-Fitness-Plans/GB-Lectures.md'
      -  Program Section:  'Goal-Based-Fitness-Plans/GB-Program-Section.md'
      -  Simple Product:  'Goal-Based-Fitness-Plans/GB-Simple-Product.md'
  -  1-on-1 Personal Training:
      -  Introduction:  '1-on-1-Personal-Training/Introduction.md'  
      -  One Time Program:  '1-on-1-Personal-Training/One-Time-Program.md' 
      -  Monthly Plans:  '1-on-1-Personal-Training/Monthly-Plans.md' 
      -  Product Bundle:  '1-on-1-Personal-Training/Product-Bundle.md' 
  -  Single Subscription:  'Single-Subscription.md'
  -  Group Subscription:  'Group-Subscription.md'
  -  Group Subscription vs Product Bundle:  'Group-Subscription-vs-Product-Bundle.md'
  -  Coupons:  'Coupons.md'
  -  Affiliate Partners:  'Affiliate-Partners.md'
theme:
  name: material
  features:
    - instant
  font:
    text: Inter
    code: Source Code Pro
  palette:
      primary: indigo
      accent: blue

plugins:
  - search:
      prebuild_index: true
      lang:
        - en
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde